package com.example.myapp.model

class SurveyDataModel {
    var id = 0

    var LOGIN_ID: String? = null
    var STATE_NAME: String? = null

    var DIST_NAME: String? = null
    var ULB_NAME: String? = null
    var DIST_ID: String? = null
    var ULB_ID: String? = null

    var ZONE_NAME: String? = null
    var WARD_NAME: String? = null
    var STATE_ID: String? = null
    var ZONE_ID: String? = null
    var WARD_ID: String? = null
    var PARINAM_NAME: String? = null
    var PARINAM_ID: String? = null
    var PARINAM_NAME_OTHER: String? = null
    var NEXT_DATE: String? = null
    var MAAP_AADHAR_NAME: String? = null
    var MAAP_AADHAR_ID: String? = null
    var PARCEL_NAME: String? = null
    var PARCEL_NOT_IN_MAP: String? = null
    var PROPERTY_NO: String? = null
    var PROPERTY_ADDRESS: String? = null
    var ROAD_STREET_NO: String? = null
    var ROAD_STREET_NAME: String? = null
    var COLONY_NAME: String? = null
    var STATION_NAME: String? = null
    var LANDMARK_NAME: String? = null
    var PINCODE: String? = null
    var LAST_PAYMENT_YEAR_SURVEYOR: String? = null
    var LAST_PAYMENT_DATE_SURVEYOR: String? = null
    var RECIEPT_NO_SURVEYOR: String? = null
    var PAID_TAX_AMOUNT: String? = null
    var LAST_PAYMENT_YEAR_CORP: String? = null
    var LAST_PAYMENT_DATE_CORP: String? = null
    var RECIEPT_NO_CORP: String? = null
    var PROPERTY_REGISTERED: String? = null
    var RESPONDENT_NAME: String? = null
    var MOBILE_NO: String? = null
    var PROPERTY_RELATION: String? = null
    var PROPERTY_RELATION_OTHER: String? = null
    var PROPERTY_RELATION_OTHER_NAME: String? = null
    var PROPERTY_OWNERSHIP_CLASSIFICATION: String? = null
    var OTHER_CLASSIFICATION_NAME: String? = null
    var LAND_TYPE: String? = null
    var LAND_TYPE_OTHER: String? = null
    var NAME: String? = null
    var HUSBAND_FATHER_NAME: String? = null
    var HOUSE_NO: String? = null
    var ROAD_STREET_NO2: String? = null
    var ROAD_STREET_NAME2: String? = null
    var COLONY_NAME2: String? = null
    var STATION_NAME2: String? = null
    var CITY: String? = null
    var STATE_NAME2: String? = null
    var PINCODE2: String? = null
    var EMAIL: String? = null
    var MOBILE_NO2: String? = null
    var INCOMETAX_PAYER: String? = null
    var FEMALE_MEMBER: String? = null
    var MALE_MEMBER: String? = null
    var FAMILY_GROUP: String? = null
    var FAMILY_RENTAL_GROUP: String? = null
    var PROPERTY_USES: String? = null
    var PROPERTY_USES_OTHER: String? = null
    var PROPERTY_USES_OTHER_REMARK1: String? = null
    var PROPERTY_USES_OTHER_REMARK2: String? = null
    var PROPERTY_USES_OTHER_REMARK3: String? = null
    var CONSTRUCTION_YEAR: String? = null
    var LAND_AREA: String? = null
    var MANJIL_CODE: String? = null
    var CONSTRUCTION_YEAR_C: String? = null
    var BUILDING_CODE: String? = null
    var FLOOR_CODE: String? = null
    var AREA_C: String? = null
    var MANJIL_USES: String? = null
    var DISCOUNT: String? = null
    var DISCOUNT_TYPE: String? = null
    var DISCOUNT_TYPE_CODE: String? = null
    var DISCOUNT_TYPE_OTHER_NAME: String? = null
    var HISTORIC_PROPERTY: String? = null
    var WATER_SUPPLY_TYPE: String? = null
    var WATER_SUPPLY_HOURS: String? = null
    var WATER_SOURCE: String? = null
    var PIPE_THICKNESS: String? = null
    var WATER_PERIOD: String? = null
    var PIPE_PRESSURE: String? = null
    var WATER_METER: String? = null
    var WATER_METER_CONDITION: String? = null
    var RAIN_WATER_HARVESTING: String? = null
    var RAIN_WATER_HARVESTING_USES: String? = null
    var SEWAGE_CONNECTION: String? = null
    var SEWAGE_NETWORK_IF_NOT: String? = null
    var TOILET_COUNT: String? = null
    var SEWAGE_TYPE: String? = null
    var TREE_COUNT: String? = null
    var WATER_TANK: String? = null
    var TWO_WHEELER: String? = null
    var FOUR_WHEELER: String? = null
    var BUILDING_PERMIT: String? = null
    var PROPERTY_IMAGE: String? = null
    var SIGNATURE_IMAGE: String? = null
    var PROPERTY_IMAGE_NAME: String? = null
    var SIGNATURE_IMAGE_NAME: String? = null
    var UNIQUE_ID: String? = null
    var GRID_NO: String? = null
    var MAP_ID: String? = null
    var UNIQUE_ID_TEXT: String? = null
    var ULB_P_ID: String? = null
    var KHASRA_NO: String? = null
    var PROPERTY_RELATION_OTHER_ID=0
    var PROPERTY_OWNERSHIP_CLASSIFICATION_ID=0
    var LAND_TYPE_ID=0
    var PROPERTY_USES_ID=0
    var PROPERTY_USES_OTHER_ID=0
    var MANJIL_ID=0
    var BUILDING_ID=0
    var FLOOR_ID=0
    var MANJIL_USES_ID=0
    var WATER_SOURCE_ID=0
    var PIPE_THICKNESS_ID=0
    var PIPE_PRESSURE_ID=0
    var WATER_METER_ID=0
    var WATER_METER_CONDITION_ID=0
    var RAIN_WATER_HARVESTING_USES_ID=0
    var SEWAGE_NETWORK_IF_NOT_ID=0
    var SEWAGE_TYPE_ID=0
    var ISUPLOADED: Boolean? = null
    var ISVISITED: Boolean? = null

}